version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: bot-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  llm_service:
    build:
      context: ./llm_service
    container_name: llm-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
